language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

jdk:
  - openjdk10

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - "sbt clean coverage test coverageReport" 

after_success:
  - bash <(curl -s https://codecov.io/bash)
