language: scala

scala:
  - 2.11.8
  - 2.12.1

jdk:
  - oraclejdk8

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - "sbt clean coverage test coverageReport" 

after_success:
  - bash <(curl -s https://codecov.io/bash)
